package io.payrun.models;

public enum RuleExclusionFlags{
None,NiMissingPayInstructionRule,TaxMissingPayInstructionRule,TaxCodeUpliftRule,NiSetExpectedLetterRule,NiDateOfBirthChangeRetrospectiveCRule,NiDefermentStatusChangeRule,NiEndContractedOutTransferRule,PaymentAfterLeavingRule,LeaverEndInstructionsRule,P45StudentLoanInstructionRule,P45TaxInstructionRule,P45YtdTaxRule,YtdInstructionRule,TaxCodeRegionChangeRule,AutoEnrolmentStatusChangeRule,EmployeeDeceasedRule
}
