package io.payrun.models;

public enum SapExclusionReason{
None,AverageWeeklyEarningsBelowLelThreshold,ExceededMaximumKeepInTouchDays,ExceededMaximumWeeks,InLegalCustody,HasDeceased,NothingToPay,SspDue,EmploymentEndedBeforeMatchingDate
}
