package io.payrun.models;

public enum SppExclusionReason{
None,InLegalCustody,HasDeceased,StillbirthBeforeWeek24,NothingToPay,AverageWeeklyEarningsBelowLelThreshold,WorkedDuringAbsence,EmploymentEndedBeforeBabyBorn,SspDue,CutOffPeriodExceeded
}
